name: Publish Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Generate package-lock.json
        run: bunx synp --source-file yarn.lock
      - name: Upload package-lock.json
        uses: actions/upload-artifact@v4
        with:
          name: lock
          path: package-lock.json
      - name: Build
        run: bun run build

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download lock
        uses: actions/download-artifact@v4
        with:
          name: lock
      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: raycast-publish
          include-hidden-files: true
          path: |
            *
            .*
            !.git/*
            !.github/*
            !yarn.lock
            !bun.lockb
      - name: Checkout code
        uses: zrr1999/publish-raycast-extension@main
        with:
          fork-repo: zrr1999/raycast-extensions
          token: ${{ secrets.PAT_TOKEN }}
          committer: zrr1999 <2742392377@qq.com>
          extension-name: commit-message-formatter
